import type { HomeFeed } from '../types/home';

export const PREVIEW_HOME: HomeFeed = {
  success: true,
  available: true,
  metro: 'GYEONGGI',
  festivals: [
    {
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
      contentId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
      source: 'tour',
      title: '수원화성문화제',
      location_name: '수원화성 행궁광장',
      latitude: 37.287,
      longitude: 127.013,
      start_date: '2026-08-19',
      end_date: '2026-09-21',
      municipality_name: '수원시',
      category: '문화/예술',
      is_trending: true,
      image_url: 'https://images.unsplash.com/photo-1549692520-acc6669e2f0c?w=800&q=80',
      tel: '031-228-3675',
      fee: '무료 (일부 유료 공연)',
      description: '세계유산 수원화성을 무대로 펼쳐지는 야간 퍼레이드와 전통 공연, 행궁 야행 프로그램이 이어집니다.',
    },
    {
      id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
      contentId: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
      source: 'tour',
      title: '용인 한국민속촌 축제',
      location_name: '한국민속촌',
      latitude: 37.259,
      longitude: 127.117,
      start_date: '2026-08-21',
      end_date: '2026-09-11',
      municipality_name: '용인시',
      category: '가족',
      is_trending: true,
      image_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80',
      tel: '031-288-0000',
      fee: '입장권 별도 · 공연 무료',
      description: '전통 가옥과 장터 체험, 가족 공연이 하루 종일 이어지는 용인 대표 가족 축제입니다.',
    },
    {
      id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
      contentId: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
      source: 'tour',
      title: '가평 자라섬 재즈페스티벌',
      location_name: '자라섬',
      latitude: 37.823,
      longitude: 127.513,
      start_date: '2026-08-22',
      end_date: '2026-09-05',
      municipality_name: '가평군',
      category: '계절축제',
      is_trending: true,
      image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
      tel: '031-582-0174',
      fee: '일권 55,000원',
      description: '북한강 위 자라섬에서 열리는 국내 대표 재즈 페스티벌. 선셋 무대와 푸드존이 함께합니다.',
    },
    {
      id: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
      contentId: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
      source: 'tour',
      title: '수원 영동시장 먹거리 축제',
      location_name: '수원 영동시장',
      latitude: 37.2762,
      longitude: 127.0168,
      start_date: '2026-08-20',
      end_date: '2026-09-09',
      municipality_name: '수원시',
      category: '먹거리',
      is_trending: true,
      image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
      tel: '031-241-1101',
      fee: '메뉴별 상이 · 쿠폰 적용가',
      description: '영동시장 골목 상인과 함께하는 먹거리 축제. 온앤온+ 상생 쿠폰으로 꼬치·분식을 할인받을 수 있습니다.',
    },
    {
      id: 'ffffffff-ffff-4fff-8fff-ffffffffffff',
      contentId: 'ffffffff-ffff-4fff-8fff-ffffffffffff',
      source: 'tour',
      title: '용인 플리마켓 위크',
      location_name: '용인 기흥구청 광장',
      latitude: 37.2755,
      longitude: 127.1148,
      start_date: '2026-08-22',
      end_date: '2026-09-01',
      municipality_name: '용인시',
      category: '플리마켓',
      is_trending: false,
      image_url: 'https://images.unsplash.com/photo-1515165562839-978bbcf01262?w=800&q=80',
      tel: '031-324-2114',
      fee: '무료',
      description: '빈티지·수공예 셀러가 모이는 용인 야외 플리마켓. 현장 피드 작성 시 지자체 매칭 포인트가 적립됩니다.',
    },
  ],
  promotions: [
    {
      id: 'dddddddd-dddd-4ddd-8ddd-dddddddd0001',
      title: '수원화성문화제 제휴 한정식 할인',
      festival_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
      festival_title: '수원화성문화제',
      business_name: '화성행궁 한정식',
      merchant_discount_rate: 5,
      gov_matching_rate: 5,
      total_discount_rate: 10,
      remaining_quantity: 200,
      funding_type: 'MATCHED',
      coupon_type: 'OFFICIAL',
      metro: 'GYEONGGI',
      municipality_name: '수원시',
      main_menu: '궁중갈비탕, 수원왕갈비, 김치찌개',
      features: '행궁 앞 30년 노포, 당일 손질 고기',
      exterior_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
      interior_image_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80',
      address: '경기도 수원시 팔달구 정조로 825',
      latitude: 37.2819,
      longitude: 127.0138,
      gps_confirmed: true,
      tel: '031-228-2800',
    },
    {
      id: 'dddddddd-dddd-4ddd-8ddd-dddddddd0002',
      title: '용인 한국민속촌 제휴 카페 할인',
      festival_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
      festival_title: '용인 한국민속촌 축제',
      business_name: '민속촌 찻집',
      merchant_discount_rate: 10,
      gov_matching_rate: 10,
      total_discount_rate: 20,
      remaining_quantity: 150,
      funding_type: 'MATCHED',
      coupon_type: 'OFFICIAL',
      metro: 'GYEONGGI',
      municipality_name: '용인시',
      main_menu: '수정과, 인절미빙수, 전통 약과',
      features: '민속촌 장터 안 한옥 카페, 야외 마당 좌석',
      exterior_image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80',
      interior_image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
      address: '경기도 용인시 기흥구 민속촌로 90',
      latitude: 37.259,
      longitude: 127.117,
      gps_confirmed: true,
      tel: '031-288-0000',
    },
    {
      id: 'self-funded-preview',
      title: '가평 자라섬 상가 자체 할인',
      festival_id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
      festival_title: '가평 자라섬 재즈페스티벌',
      business_name: '자라섬 푸드트럭',
      merchant_discount_rate: 15,
      gov_matching_rate: 0,
      total_discount_rate: 15,
      remaining_quantity: 80,
      funding_type: 'MERCHANT_ONLY',
      coupon_type: 'SELF',
      metro: 'GYEONGGI',
      municipality_name: '가평군',
      main_menu: '수제버거, 레모네이드, 콘치즈',
      features: '선셋 무대 앞 푸드존, 현장 조리',
      exterior_image_url: 'https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?w=800&q=80',
      interior_image_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80',
      address: '경기도 가평군 가평읍 자라섬로 60',
      latitude: 37.823,
      longitude: 127.513,
      gps_confirmed: true,
      tel: '031-582-0174',
    },
  ],
  popular: [],
};

PREVIEW_HOME.popular = PREVIEW_HOME.festivals;
