import type { HomeFeed } from '../types/home';

export const PREVIEW_HOME: HomeFeed = {
  success: true,
  available: true,
  metro: 'GYEONGGI',
  festivals: [
    {
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
      contentId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
      source: 'tour',
      title: '수원화성문화제',
      location_name: '수원화성 행궁광장',
      latitude: 37.287,
      longitude: 127.013,
      start_date: '2026-08-19',
      end_date: '2026-09-21',
      municipality_name: '수원시',
      category: '문화/예술',
      is_trending: true,
      image_url: 'https://images.unsplash.com/photo-1549692520-acc6669e2f0c?w=800&q=80',
    },
    {
      id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
      contentId: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
      source: 'tour',
      title: '용인 한국민속촌 축제',
      location_name: '한국민속촌',
      latitude: 37.259,
      longitude: 127.117,
      start_date: '2026-08-21',
      end_date: '2026-09-11',
      municipality_name: '용인시',
      category: '가족',
      is_trending: true,
      image_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80',
    },
    {
      id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
      contentId: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
      source: 'tour',
      title: '가평 자라섬 재즈페스티벌',
      location_name: '자라섬',
      latitude: 37.823,
      longitude: 127.513,
      start_date: '2026-08-22',
      end_date: '2026-09-05',
      municipality_name: '가평군',
      category: '계절축제',
      is_trending: true,
      image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
    },
    {
      id: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
      contentId: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
      source: 'tour',
      title: '수원 영동시장 먹거리 축제',
      location_name: '수원 영동시장',
      latitude: 37.2762,
      longitude: 127.0168,
      start_date: '2026-08-20',
      end_date: '2026-09-09',
      municipality_name: '수원시',
      category: '먹거리',
      is_trending: true,
      image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    },
    {
      id: 'ffffffff-ffff-4fff-8fff-ffffffffffff',
      contentId: 'ffffffff-ffff-4fff-8fff-ffffffffffff',
      source: 'tour',
      title: '용인 플리마켓 위크',
      location_name: '용인 기흥구청 광장',
      latitude: 37.2755,
      longitude: 127.1148,
      start_date: '2026-08-22',
      end_date: '2026-09-01',
      municipality_name: '용인시',
      category: '플리마켓',
      is_trending: false,
      image_url: 'https://images.unsplash.com/photo-1515165562839-978bbcf01262?w=800&q=80',
    },
  ],
  promotions: [
    {
      id: 'dddddddd-dddd-4ddd-8ddd-dddddddd0001',
      title: '수원화성문화제 제휴 한정식 할인',
      festival_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
      festival_title: '수원화성문화제',
      business_name: '화성행궁 한정식',
      merchant_discount_rate: 5,
      gov_matching_rate: 5,
      total_discount_rate: 10,
      remaining_quantity: 200,
      funding_type: 'MATCHED',
    },
    {
      id: 'dddddddd-dddd-4ddd-8ddd-dddddddd0002',
      title: '수원화성문화제 제휴 카페 할인',
      festival_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
      festival_title: '수원화성문화제',
      business_name: '팔달문 카페',
      merchant_discount_rate: 10,
      gov_matching_rate: 10,
      total_discount_rate: 20,
      remaining_quantity: 150,
      funding_type: 'MATCHED',
    },
    {
      id: 'self-funded-preview',
      title: '영동시장 상가 자체 할인',
      festival_id: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
      festival_title: '수원 영동시장 먹거리 축제',
      business_name: '남문시장 분식',
      merchant_discount_rate: 15,
      gov_matching_rate: 0,
      total_discount_rate: 15,
      remaining_quantity: 80,
      funding_type: 'MERCHANT_ONLY',
    },
  ],
  popular: [],
};

PREVIEW_HOME.popular = PREVIEW_HOME.festivals;
